import type { Env, ImageInfo, OutputFormat } from "./types";
import { OUTPUT_MIME } from "./utils";
const MAX_DIMENSION=12000;
export interface UpscaleResult{body:ArrayBuffer;contentType:string;inputWidth:number;inputHeight:number;outputWidth:number;outputHeight:number;}
export class UpscaleError extends Error{readonly code:string;constructor(code:string,message:string){super(message);this.code=code;}}
const streamFrom=(bytes:ArrayBuffer)=>new Blob([bytes]).stream();
function outputDimensions(info:ImageInfo,scale:2|4){const width=Math.round(info.width*scale),height=Math.round(info.height*scale);if(width>MAX_DIMENSION||height>MAX_DIMENSION)throw new UpscaleError("OUTPUT_TOO_LARGE",`The ${scale}× result would be ${width} × ${height}px. The maximum dimension is ${MAX_DIMENSION}px.`);return{width,height};}
async function cloudflare(env:Env,bytes:ArrayBuffer,scale:2|4,format:OutputFormat):Promise<UpscaleResult>{const info=await env.IMAGES.info(streamFrom(bytes));if(!info.width||!info.height)throw new UpscaleError("INVALID_IMAGE","Cloudflare could not read the image dimensions.");const dims=outputDimensions(info,scale);const output=await env.IMAGES.input(streamFrom(bytes)).transform({width:dims.width,height:dims.height,fit:"contain",sharpen:1}).output({format:OUTPUT_MIME[format],quality:format==="png"?undefined:90,anim:false});const response=output.response();if(!response.ok||!response.body)throw new UpscaleError("TRANSFORM_FAILED","Cloudflare Images could not generate the result.");return{body:await response.arrayBuffer(),contentType:OUTPUT_MIME[format],inputWidth:info.width,inputHeight:info.height,outputWidth:dims.width,outputHeight:dims.height};}
async function remote(env:Env,bytes:ArrayBuffer,inputType:string,scale:2|4,format:OutputFormat):Promise<UpscaleResult>{if(!env.UPSCALE_API_URL)throw new UpscaleError("PROVIDER_NOT_CONFIGURED","UPSCALE_API_URL is required for the remote provider.");const info=await env.IMAGES.info(streamFrom(bytes));const dims=outputDimensions(info,scale);const form=new FormData();form.set("image",new File([bytes],"input",{type:inputType}));form.set("scale",String(scale));form.set("format",format);const headers=new Headers();if(env.UPSCALE_API_TOKEN)headers.set("authorization",`Bearer ${env.UPSCALE_API_TOKEN}`);const response=await fetch(env.UPSCALE_API_URL,{method:"POST",headers,body:form});if(!response.ok||!response.body)throw new UpscaleError("PROVIDER_FAILED",`The AI upscale provider returned HTTP ${response.status}.`);const contentType=response.headers.get("content-type")||OUTPUT_MIME[format];if(!contentType.startsWith("image/"))throw new UpscaleError("PROVIDER_INVALID_RESPONSE","The AI provider did not return an image.");return{body:await response.arrayBuffer(),contentType,inputWidth:info.width,inputHeight:info.height,outputWidth:dims.width,outputHeight:dims.height};}
export function upscale(env:Env,bytes:ArrayBuffer,inputType:string,scale:2|4,format:OutputFormat){return env.UPSCALE_PROVIDER==="remote"?remote(env,bytes,inputType,scale,format):cloudflare(env,bytes,scale,format);}
