import type { JobRecord, OutputFormat } from "./types";
export const SUPPORTED_INPUT_TYPES = new Set(["image/jpeg","image/png","image/webp"]);
export const OUTPUT_MIME:Record<OutputFormat,string>={png:"image/png",jpeg:"image/jpeg",webp:"image/webp"};
export function json(data:unknown,init:ResponseInit={}):Response{const headers=new Headers(init.headers);headers.set("content-type","application/json; charset=utf-8");headers.set("cache-control","no-store");headers.set("x-content-type-options","nosniff");return new Response(JSON.stringify(data),{...init,headers});}
export function errorResponse(status:number,code:string,message:string):Response{return json({error:{code,message}},{status});}
export function parseScale(value:FormDataEntryValue|null):2|4|null{return value==="2"?2:value==="4"?4:null;}
export function parseFormat(value:FormDataEntryValue|null):OutputFormat|null{return value==="png"||value==="jpeg"||value==="webp"?value:null;}
export function extensionFor(format:OutputFormat):string{return format==="jpeg"?"jpg":format;}
export function safeDownloadName(name:string,scale:number,format:OutputFormat):string{const base=name.replace(/\.[^.]+$/,"").replace(/[^a-zA-Z0-9._-]+/g,"-").replace(/^-+|-+$/g,"")||"image";return `${base}-${scale}x.${extensionFor(format)}`;}
export function publicJob(job:JobRecord){return{id:job.id,status:job.status,originalName:job.original_name,scale:job.scale,outputFormat:job.output_type,inputBytes:job.input_bytes,outputBytes:job.output_bytes,inputWidth:job.input_width,inputHeight:job.input_height,outputWidth:job.output_width,outputHeight:job.output_height,error:job.error_code?{code:job.error_code,message:job.error_message}:null,createdAt:job.created_at,expiresAt:job.expires_at,originalUrl:`/api/jobs/${job.id}/original`,resultUrl:job.status==="completed"?`/api/jobs/${job.id}/result`:null,downloadUrl:job.status==="completed"?`/api/jobs/${job.id}/result?download=1`:null};}
export function getJobId(pathname:string):{id:string;resource?:"original"|"result"}|null{const match=pathname.match(/^\/api\/jobs\/([0-9a-f-]{36})(?:\/(original|result))?$/i);if(!match?.[1])return null;return{id:match[1],resource:match[2] as "original"|"result"|undefined};}
export function isLikelyImage(bytes:Uint8Array,mime:string):boolean{if(mime==="image/jpeg")return bytes[0]===0xff&&bytes[1]===0xd8&&bytes[2]===0xff;if(mime==="image/png")return bytes.slice(0,8).every((v,i)=>v===[137,80,78,71,13,10,26,10][i]);if(mime==="image/webp")return String.fromCharCode(...bytes.slice(0,4))==="RIFF"&&String.fromCharCode(...bytes.slice(8,12))==="WEBP";return false;}
